services:
  rnacos:
    container_name: rnacos
    image: docker.io/qingpan/rnacos:stable
    ports:
      - "8848:8848" # http
      - "9848:9848" # grpc
      - "10848:10848" # 控制台
    volumes:
      - ./tmp:/io:rw
    environment:
      - RNACOS_INIT_ADMIN_USERNAME=admin
      - RNACOS_INIT_ADMIN_PASSWORD=admin
      - RNACOS_HTTP_PORT=8848
    restart: unless-stopped  # 可选：容器异常时自动重启

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./tmp/prometheus_data:/prometheus
    ports:
      - "9090:9090"
    restart: unless-stopped
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'

  api-gateway:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./api/config/test.toml:/app/config.toml
    
  order:
    build:
      context: .
      dockerfile: rpc/order/Dockerfile
    ports:
      - "8082:8082"
    volumes:
      - ./rpc/order/config/test.toml:/app/config.toml
    
  user:
    build:
      context: .
      dockerfile: rpc/user/Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - ./rpc/user/config/test.toml:/app/config.toml
