services:
  rnacos:
    container_name: rnacos
    image: docker.io/qingpan/rnacos:stable
    ports:
      - "8848:8848" # http
      - "9848:9848" # grpc
      - "10848:10848" # 控制台
    volumes:
      - ./tmp:/io:rw
    environment:
      - RNACOS_INIT_ADMIN_USERNAME=admin
      - RNACOS_INIT_ADMIN_PASSWORD=admin
      - RNACOS_HTTP_PORT=8848
    restart: unless-stopped  # 可选：容器异常时自动重启
