# 服务运行端口
port=8081
disable_metrics=true
# 服务发现 server discover
[sd]
[sd.nacos]
server_addr="10.64.133.21:8848"
namespace="public"
username=""
password=""
# 用于注册到nacos时用的服务名称
service_name="volo-boot-user.rpc"