[package]
name = "common"
version = "0.1.0"
edition = "2021"

[lib]

[dependencies]
tracing = "0.1"
tracing-appender = "0.2"
tracing-subscriber = { version = "0.3", features = ["default", "env-filter", "fmt", "chrono", "time", "local-time"] }
atty = "0.2"  # 用于检测终端是否支持 ANSI 颜色
